#!/bin/bash
usage="$(basename "$0") [show|list] [--help] name_of_backup -- program to help backup directories before making major changes

where:
    show|list         show this help text
    name_of_backup    name of project to backup in ../backup/THIS_DIR_NAME/name_of_backup
    --help           shows this help text"

seed=42
while getopts ':help:' option; do
  case "$option" in
    help) echo "$usage"
       exit
       ;;
    show) echo "$usage"
       exit
       ;;
    s) seed=$OPTARG
       ;;
    :) printf "missing argument for -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit 1
       ;;
  esac
done
shift $((OPTIND - 1))

if [ $1 == "show" ] || [ $1 == "list" ]; then
  DIRECTORY="../backup"
  NAMEOFBACKUP=$1
  PROJECTNAME="$(basename $PWD)"
  PROJECTDIRECTORY="$DIRECTORY/$PROJECTNAME"

  echo "List of backups:"
  #work ls -lt $PROJECTDIRECTORY | grep -v '^total' | awk '{printf("   %-40s%s %-8s %s\n", $10, $7, $8, $9); }'
  #home ls -lt $PROJECTDIRECTORY | grep -v '^total' | awk '{printf("   %-40s%s %-8s %s\n", $9, $6, $7, $8); }'
  ls -lt $PROJECTDIRECTORY | grep -v '^total' | rev | awk 'function rev(str) {
    nstr = ""
    for(i = 1; i <= length(str); i++) {
      nstr = substr(str,i,1) nstr
    }

    return nstr
  }
  { printf("   %-40s%s %-8s %s\n", rev($1), rev($4), rev($3), rev($2)); }'
  exit 1
fi

# set up variables
DIRECTORY="../backup"
NAMEOFBACKUP=$1

# make backup dir if doesnt exist
# make backup dir if doesnt exist
# make backup dir if doesnt exist
# ../backup

if [ ! -d "$DIRECTORY" ]; then
  mkdir $DIRECTORY
#else
#  echo "log: backup already exists"t
fi

# make directory in backup dir
# make directory in backup dir
# make directory in backup dir
# ../backup/project

PROJECTNAME="$(basename $PWD)"
PROJECTDIRECTORY="$DIRECTORY/$PROJECTNAME"

if [ ! -d "$PROJECTDIRECTORY" ]; then
  mkdir $PROJECTDIRECTORY
fi

# make name of direcotry in project dir
# make name of direcotry in project dir
# make name of direcotry in project dir
# ../backup/project/myBackup123

NEWDIRECTORY="$PROJECTDIRECTORY/$NAMEOFBACKUP"
# make sure backup name doesn't exist
if [  -d "$NEWDIRECTORY" ]; then
  echo "backup with this name already exists"
  exit 1
else
  mkdir $NEWDIRECTORY
fi

cp -r ./ $NEWDIRECTORY
echo success!
echo "new backup for $PROJECTDIR created at $NEWDIRECTORY"
